export const LogicEvent = {
  robLoginUI: "robLoginUI",
  enterMap: "enter_map",
  enterLogin: "enter_login",
  showToast: "show_toast",
  showWaiting: "show_waiting",
  hideWaiting: "hide_waiting",
  showTip: "show_tip",
  createRole: "createRole",
  enterServerComplete: "enterServerComplete",
  loginComplete: "login_complete",

  touchMap: "touch_map",
  moveMap: "move_map",
  beforeScrollToMap: "before_scroll_to_map",
  mapCenterChange: "map_center_change",
  scrollToMap: "scroll_to_map",
  mapShowAreaChange: "map_show_area_change",

  updateArmy: "update_army",
  updateArmyList: "update_army_list",
  updateTag: "update_tag",
  updateBuilds: "update_builds",
  updateBuild: "update_build",
  deleteBuild: "delete_build",
  updateCities: "update_citys",
  updateCity: "update_city",
  updateChatHistory: "update_chat_history",
  unionChange: "union_change",

  openCityAbout: "open_city_about",
  closeCityAbout: "close_city_about",
  openFortressAbout: "open_fortress_about",
  openFacility: "open_facility",
  openArmySetting: "open_army_setting",
  updateMyRoleRes: "upate_my_roleRes",
  openGeneralDes: "open_general_des",
  openGeneralChoose: "open_general_choose",
  openArmySelectUi: "open_army_select_ui",
  openDrawResult: "open_draw_result",
  interiorCollect: "interior_collect",
  interiorOpenCollect: "interior_openCollect",
  openGeneralConvert: "open_general_convert",
  openGeneralRoster: "open_general_roster",
  openGeneral: "open_general",
  openSkill: "open_skill",
  closeSkill: "close_skill",
  openSkillInfo: "open_skillInfo",

  openWarReport: "open_war_report",
  openDraw: "open_draw",
  openUnion: "open_union",
  openCollection: "open_collection",
  openTransform: "open_transform",
  openChat: "open_chat",
  openSetting: "open_setting",
} as const;
